// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package elbiface_test

import (
	"testing"

	"github.com/tetrafolium/aws-sdk-go/service/elb"
	"github.com/tetrafolium/aws-sdk-go/service/elb/elbiface"
	"github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*elbiface.ELBAPI)(nil), elb.New(nil))
}
