// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package elastictranscoderiface_test

import (
	"testing"

	"github.com/tetrafolium/aws-sdk-go/service/elastictranscoder"
	"github.com/tetrafolium/aws-sdk-go/service/elastictranscoder/elastictranscoderiface"
	"github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*elastictranscoderiface.ElasticTranscoderAPI)(nil), elastictranscoder.New(nil))
}
