// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package swfiface_test

import (
	"testing"

	"github.com/tetrafolium/aws-sdk-go/service/swf"
	"github.com/tetrafolium/aws-sdk-go/service/swf/swfiface"
	"github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*swfiface.SWFAPI)(nil), swf.New(nil))
}
